helm-extra-args: --timeout 600s
check-version-increment: true
debug: true
remote: origin
target-branch: main
chart-dirs:
  - charts
test-values: |
  geth=charts/geth/ci/values.yaml
  lighthouse=charts/lighthouse/ci/values.yaml