image:
  repository: berachain
  tag: notreal

storage:
  storageClassName: local
  pvcSize: 1200Gi

replicas: 1

resources:
  limits:
    cpu: 8
    memory: 64Gi
  requests:
    cpu: 4
    memory: 64Gi

berachain:
  role: full
  chainId: ''
  genesisUrl: ''
  binUrl: ''
  keyringBackend: file
  pruningMode: default
  seeds: ''
  minGasPrices: '0b/0x5806E416dA447b267cEA759358cF22Cc41FAE80F'
  dbBackend: goleveldb
  persistentPeers: ''
  privatePeerIds: ''
  pexEnabled: true
  telemetry:
    enabled: false
    dogstatsdAddr: ''
  prometheus:
    enabled: true
  p2p:
    hostPorts: false
    tcpPort: 26656
    udpPort: 26656
    externalAddress: ''
    seedModeEnabled: false
    stateSyncEnabled: false
    stateSyncRpcServers: ''
  grpc:
    enabled: true
  rpc:
    corsAllowedOrigins: '[]'
    maxInboundPeers: 10
    maxOutboundPeers: 15
  api:
    enabled: false
    unsafeCorsEnabled: false

  polaris:
    chainId: '1'
