image:
  repository: berad
  tag: notreal

storage:
  storageClassName: local
  pvcSize: 1200Gi

# nodeSelector is optional. Uncomment to use.
# nodeSelector:
#   key: value

replicas: 1

resources:
  limits:
    cpu: 16
    memory: 64Gi
  requests:
    cpu: 4
    memory: 64Gi

berachain:
  role: full
 # priv_validator_key_json: ''
 # priv_validator_state_json: ''
 # node_key_json: ''
  chainId: ''
  genesisUrl: ''
  keyringBackend: file
  pruningMode: default
  seeds: ''
  minGasPrices: '10000000abgt'
  dbBackend: goleveldb
  persistentPeers: ''
  privatePeerIds: ''
  pexEnabled: true
  stateSyncEnabled: false
  stateSyncRpcServers: ''
  telemetry:
    enabled: false
    dogstatsdAddr: ''
  prometheus:
    enabled: true
  p2p:
    hostPorts: false
    tcpPort: 26656
    udpPort: 26656
    externalAddress: ''
    seedModeEnabled: false
    maxInboundPeers: 40
    maxOutboundPeers: 20
  grpc:
    enabled: true
  rpc:
    corsAllowedOrigins: '[]'
  api:
    enabled: false
    unsafeCorsEnabled: false

  polaris:
    chainId: '1'
    optimisticExecution: false
    etherbase: '0xAf15f95bed0D3913a29092Fd7837451Ce4de64D3'
