---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "berachain.serviceAccountName" . }}-ns-admin-binding
  labels:
{{ include "berachain.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "berachain.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
