{{- if .Values.berachain.priv_validator_state_json }}
apiVersion: v1
kind: Secret
metadata:
  name: valstate
data:
  priv_validator_state.json: {{ .Values.berachain.priv_validator_state_json | b64enc }}
{{- end }}
