{{- if .Values.berachain.priv_validator_key_json }}
apiVersion: v1
kind: Secret
metadata:
  name: valkey
data:
  priv_validator_key.json: {{ .Values.berachain.priv_validator_key_json | b64enc }}
{{- end }}
