---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: berad
  labels:
{{ include "berachain.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: berad
  selector:
    matchLabels:
{{ include "berachain.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "berachain.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "berachain.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: berad
        image: {{ include "berachain.image" . }}
        {{- with .Values.berachain }}
        command:
        - berad
        args:
        - start
        - --home=/home/bera/.berad
        imagePullPolicy: IfNotPresent
        ports:
          - name: p2p
            containerPort: {{ .p2p.tcpPort }}
            protocol: TCP
          {{- if .rpc.enabled }}
          - name: rpc
            containerPort: 26657
            protocol: TCP
          {{- end }}
          {{- if .api.enabled }}
          - name: api
            containerPort: 1317
            protocol: TCP
          {{- end }}
          {{- if .grpc.enabled }}
          - name: grpc
            containerPort: 9090
            protocol: TCP
          {{- end }}
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 120
          tcpSocket:
            port: p2p
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: p2p
        startupProbe:
          initialDelaySeconds: 120
          tcpSocket:
            port: p2p
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: chaindata
          mountPath: /home/bera/.berad/data
        - name: app-config
          mountPath: /home/bera/.berad/config/app.toml
          subPath: app.toml
        - name: config-config
          mountPath: /home/bera/.berad/config/config.toml
          subPath: config.toml
      enableServiceLinks: false
      terminationGracePeriodSeconds: 300
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        readOnlyRootFilesystem: 'true'
      volumes:
      - name: app-config
        configMap:
          name: berad-app-config
      - name: config-config
        configMap:
          name: berad-config-config
  volumeClaimTemplates:
  - apiVersion: v1
    metadata:
      name: chaindata
      labels:
{{ include "berachain.labels" . | indent 8 }}
    spec:
      storageClassName: {{ .Values.storage.storageClassName }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.storage.pvcSize }}
