apiVersion: v2
name: geth
description: A Helm chart for running geth (ethereum execution engine)
type: application
version: "0.9.0"
appVersion: "v1.16.8"
maintainers:
  - email: rnodec@pm.me
    name: rnodec
