apiVersion: v2
name: geth
description: A Helm chart for running geth (ethereum execution engine)

type: application

version: "0.1.1"

appVersion: "1.10.26"

maintainers:
- email: rnodec@pm.me
  name: rnodec
