---
image:
  repository: ethereum/client-go
  tag: latest

storage:
  storageClassName: standard
  pvcSize: 40Gi

# geth:
  # network: mainnet
  # generate this value with: 'openssl rand -hex 32 | tr -d "\n"'
  # if not jwt provided, geth will auto-generate a secret under /chaindata/geth/jwtsecret
  # jwt:
