---
image:
  repository: ethereum/client-go
  tag: v1.10.26

storage:
  storageClassName: standard
  pvcSize: 40Gi

rbac:
  create: true

serviceAccount:
  create: true
  name: geth

geth:
  network: mainnet

  # generate this value with: 'openssl rand -hex 32 | tr -d "\n"'
  # if not jwt provided, geth will auto-generate a secret under /chaindata/geth/jwtsecret
  # if you do provide the jwt, do not include the leading "0x"
  # jwt:

  ipcDisable: true
