---
apiVersion: v1
kind: Service
metadata:
  name: geth
  labels:
    app: geth
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: http
      protocol: TCP
      name: http
    - port: 8551
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    app: geth
