---
storage:
  storageClassName: "standard"
  pvcSize: 10Gi

lighthouse:
  beacon:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi

  validator:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
