{{- if .Values.lighthouse.beacon.enabled -}}
---
apiVersion: v1
data:
  jwt: {{ include "lighthouse.jwt" . }}
kind: Secret
metadata:
  name: lh-jwt
  labels:
{{ include "lighthouse.labels" . | indent 4 }}
{{- end }}