{{- if eq .Values.lighthouse.role "beacon" }}
---
apiVersion: v1
data:
  jwt: {{ include "lighthouse.jwt" .Values.lighthouse }}
kind: Secret
metadata:
  name: lh-jwt
  labels:
{{ include "lighthouse.labels" . | indent 4 }}
{{- end }}