{{- if eq .Values.lighthouse.role "beacon" }}
---
apiVersion: v1
data:
  jwt.token: {{ required ".Values.lighthouse.beacon.execution_endpoint.jwt required in beacon mode" .Values.lighthouse.beacon.execution_endpoint.jwt | b64enc | quote }}
kind: Secret
metadata:
  name: lh-jwt
  labels:
{{ include "lighthouse.labels" . | indent 4 }}
{{- end }}