{{- $existingRole := lookup "rbac.authorization.k8s.io/v1" "Role" .Release.Namespace "namespace-admin" }}
{{- if not $existingRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  labels:
{{ include "lighthouse.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
{{- end }}
