{{- $lhrole := "beacon" -}}
{{- if .Values.lighthouse.role -}}
{{- $lhrole = .Values.lighthouse.role -}}
{{- end -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  labels:
{{ include "lighthouse.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: lighthouse
  selector:
    matchLabels:
{{ include "lighthouse.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "lighthouse.labels" . | indent 8 }}
    spec:
      serviceAccount: {{ include "lighthouse.serviceAccountName" . }}
      serviceAccountName: {{ include "lighthouse.serviceAccountName" . }}     
      {{- if eq $lhrole "beacon" }}
      volumes:
       - name: jwt
         secret:
           secretName: lh-jwt
      {{- end }}
      containers:
      - name: lighthouse
        image: {{ include "lighthouse.image" . }}
        imagePullPolicy: IfNotPresent
        command: 
        - lighthouse 
        - {{ $lhrole }}
        args:
        {{ with .Values.lighthouse -}}
        - --network={{ .network }}
        - --datadir=/chaindata
        {{- if eq $lhrole "beacon" }}
        - --http
        - --prune-payloads=false
        - --disable-upnp
        {{- $beacon := default dict .beacon -}}
        {{- if $beacon.execution_endpoint }}
        - --execution-endpoint=http://{{- $beacon.execution_endpoint.host -}}:{{- $beacon.execution_endpoint.port }}
        - --execution-jwt=/etc/eth2/jwt
        {{- end }}
        {{- if $beacon.checkpoint_sync.enabled }}
        - --checkpoint-sync-url={{- required "lighthouse.beacon.checkpoint_sync.url is required when checkpoint_sync is enabled" $beacon.checkpoint_sync.url -}}
        {{- end }}
        {{- end }}
        {{- if eq $lhrole "vc" }}
        {{ with .validator -}}
        {{- if .graffiti }}
        - --graffiti={{ .graffiti | quote }}
        {{- end }}
        {{- if .fee_recipient }}
        - --suggested-fee-recipient={{ .fee_recipient | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        ports:
          - name: http
            containerPort: 5052
            protocol: TCP
          - name: tcppeer
            containerPort: 9000
            protocol: TCP
          - name: udppeer
            containerPort: 9000
            protocol: UDP
        livenessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          terminationGracePeriodSeconds: 60
          exec:
            command: 
            - cat
            - /chaindata/beacon/network/enr.dat
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          exec:
            command: 
            - cat 
            - /chaindata/beacon/network/enr.dat
        startupProbe:
          initialDelaySeconds: 120
          exec:
            command: 
            - cat 
            - /chaindata/beacon/network/enr.dat
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 1Gi  
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:  
              - ALL
        volumeMounts:
        - name: chaindata
          mountPath: /chaindata
        {{- if eq $lhrole "beacon" }}
        - name: jwt
          mountPath: /etc/eth2
        {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - apiVersion: v1
    metadata:
      name: chaindata
      labels:
{{ include "lighthouse.labels" . | indent 8 }}
    spec:
      storageClassName: {{ .Values.storage.storageClassName }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.storage.pvcSize }}
