{{- if and .Values.lighthouse.validator.ingress.http.enabled .Values.lighthouse.validator.http.enabled  }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lighthouse-bn-http
  labels:
{{ include "lighthouse.labels" . | indent 4 }}
  {{- with .Values.lighthouse.validator.ingress.http.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- with .Values.lighthouse.validator.ingress.http.tls }}
  tls:
{{ toYaml . | indent 4 }}
  {{- end }}
  rules:
    {{- range .Values.lighthouse.validator.ingress.http.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: lighthouse
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
