{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "geth.serviceAccountName" . }}
  labels:
{{ include "geth.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
{{- end }}
