{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace geth-jwt }}
{{- if not $existingSecret }}
---
apiVersion: v1
data:
  jwt: {{ include "geth.jwt" .Values.lighthouse }}
kind: Secret
metadata:
  name: geth-jwt
  labels:
{{ include "geth.labels" . | indent 4 }}
{{- end }}