---
apiVersion: v1
kind: Service
metadata:
  name: geth
  labels:
{{ include "geth.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: http
      protocol: TCP
      name: http
    - port: 8551
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
{{ include "geth.labels" . | indent 4 }}

