---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
  labels:
{{ include "geth.labels" . | indent 4 }}
spec:
  replicas: 2
  serviceName: geth
  selector:
    matchLabels:
{{ include "geth.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "geth.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "geth.serviceAccountName" . }}
      containers:
      - name: geth
        image: {{ include "geth.image" . }}
        command: 
        - geth
        args:
        {{- with .Values.geth }}
        - --{{ .network }}
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --authrpc.addr=0.0.0.0
        - --authrpc.port=8551 
        - --ipcdisable
        - --datadir=/chaindata
        {{- if .jwt }}
        - --authrpc.jwtsecret=/etc/eth2/jwt.token
        {{- end }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
          - name: rpc
            containerPort: 8551
            protocol: TCP
          - name: http
            containerPort: 8545
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: / 
            port: http
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:  
              - ALL
        volumeMounts:
        - name: chaindata
          mountPath: /chaindata
        {{- if .Values.geth.jwt }}
        - name: jwt
          mountPath: /etc/eth2
        {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      {{- if .Values.geth.jwt }}
      volumes:
       - name: jwt
         secret:
           secretName: geth-jwt
      {{- end }}
  volumeClaimTemplates:
  - apiVersion: v1
    metadata:
      name: chaindata
      labels:
{{ include "geth.labels" . | indent 8 }}
    spec:
      storageClassName: {{ .Values.storage.storageClassName }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.storage.pvcSize }}
