{{- $geth := .Values.geth | default dict }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
  labels:
    app: geth
spec:
  replicas: 2
  serviceName: geth
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      serviceAccountName: geth
      {{- if $geth.jwt -}}    
      volumes:
       - name: jwt
         secret:
           secretName: jwt
      {{- end }}
      containers:
      - name: geth
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        command: 
        - geth
        args:
        - --{{ $geth.network | default ("mainnet") }}
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --authrpc.addr=0.0.0.0
        - --authrpc.port=8551 
        - --ipcdisable
        - --datadir=/chaindata
        {{- if $geth.jwt -}}    
        - --authrpc.jwtsecret=/etc/eth2/jwt.token
        {{- end }}
        ports:
          - name: rpc
            containerPort: 8551
            protocol: TCP
          - name: http
            containerPort: 8545
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: / 
            port: http
        volumeMounts:
        - name: chaindata
          mountPath: /chaindata
        {{- if $geth.jwt -}}    
        - name: jwt
          mountPath: /etc/eth2
        {{- end }}
  volumeClaimTemplates:
  - apiVersion: v1
    metadata:
      name: chaindata
      labels:
        app: geth
    spec:
      storageClassName: "{{ .Values.storage.storageClassName }}"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "{{ .Values.storage.pvcSize }}"

