---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
  labels:
{{ include "geth.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: geth
  selector:
    matchLabels:
{{ include "geth.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "geth.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "geth.serviceAccountName" . }}
      containers:
      - name: geth
        image: {{ include "geth.image" . }}
        command: 
        - geth
        args:
        {{- with .Values.geth }}
        - --{{ .network }}
        - --datadir=/chaindata
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.vhosts=*
        - --authrpc.addr=0.0.0.0
        - --authrpc.port=8551 
        - --authrpc.vhosts=*
        - --authrpc.jwtsecret=/etc/eth2/jwt
        {{- if .ipcDisable }}
        - --ipcdisable
        {{- end -}}
        {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
          - name: rpc
            containerPort: 8551
            protocol: TCP
          - name: http
            containerPort: 8545
            protocol: TCP
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 120
          terminationGracePeriodSeconds: 60
          tcpSocket:
            port: http
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: http
        startupProbe:
          initialDelaySeconds: 120
          tcpSocket:
            port: http
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 1Gi       
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:  
              - ALL
        volumeMounts:
        - name: chaindata
          mountPath: /chaindata
        - name: jwt
          mountPath: /etc/eth2
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      volumes:
       - name: jwt
         secret:
           secretName: geth-jwt
  volumeClaimTemplates:
  - apiVersion: v1
    metadata:
      name: chaindata
      labels:
{{ include "geth.labels" . | indent 8 }}
    spec:
      storageClassName: {{ .Values.storage.storageClassName }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.storage.pvcSize }}
