apiVersion: v2
name: lighthouse
description: A Helm chart for running lighthouse (ethereum connsensus client)
type: application
version: "3.0.0"
appVersion: "v7.0.0"
maintainers:
  - email: rnodec@pm.me
    name: rnodec
