---
image:
  repository: sigp/lighthouse
  tag: v3.4.0

storage:
  storageClassName: standard
  pvcSize: 40Gi

rbac:
  create: true

replicas: 1

resources:
  # These default resources are for testing purposes
  # If you actually want to run a node, use the more realistic values which are commented out.
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi     
  # limits:
  #   cpu: 4
  #   memory: 16Gi
  # requests:
  #   cpu: 2
  #   memory: 8Gi    

serviceAccount:
  create: true
  name: lighthouse

lighthouse:
  network: mainnet
  role: beacon

  metrics:
    enabled: true

  beacon:

    # use a checkpoint sync provider to speed up syncs from scratch
    checkpoint_sync:
      enabled: true
      url: https://mainnet.checkpoint.sigp.io

    # all of these values are required if in beacon mode.  a consensus client requires an execution layer.
    # however, if they are not provided, lighthouse pod should still deploy and run for long enough to satisfy liveness and readiness probes
    # jwt must not include a leading '0x'
    # execution_endpoint:
      # host:
      # port:
      # jwt:
  # validator:
  #  fee_recipient
  #  graffiti:
