---
image:
  repository: sigp/lighthouse
  tag: v4.1.0

storage:
  storageClassName: local
  pvcSize: 1200Gi

replicas: 1

resources:
  limits:
    cpu: 5
    memory: 12Gi
  requests:
    cpu: 2
    memory: 8Gi

lighthouse:
  network: mainnet
  role: beacon

  metrics:
    enabled: false

  http:
    enabled: true

  ### BEACON ###
  beacon:

    # use a checkpoint sync provider to speed up syncs from scratch
    checkpoint_sync:
      enabled: false
      url: https://mainnet.checkpoint.sigp.io

    # this defines the connection to the execution layer - required by a consensus client like lighthouse
    # all of these values are required if in beacon mode
    # however, if they are not provided, lighthouse pod should still deploy and run for long enough to satisfy liveness and readiness probes, so you can still check things out
    # jwt must not include a leading '0x'
    execution_endpoint:
      # host:
      # port:
      # jwt:

    # you most likely want to set this
    # this is how eth peers will target you. this address and port must be accessible from the outside to your beacon node
    enr:
      host:
      port: 9000

  ### VALIDATOR ###
  validator:
  #  fee_recipient
  #  graffiti:
