---
name: Chart Testing

on:
  pull_request:
    types: 
      - opened
      - synchronize
    paths-ignore:
      - README.md

jobs:

  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest geth release
        id: geth-version
        run: |
          gv=$(curl -s https://api.github.com/repos/ethereum/go-ethereum/releases/latest | jq .tag_name -r)
          echo "geth-version=$gv" >> $GITHUB_OUTPUT

      - name: Build Github Job Summary
        run: |
          echo "# helm chart testing" >> $GITHUB_STEP_SUMMARY
          echo "geth version: ${{ steps.geth-version.outputs.geth-version }}" >> $GITHUB_STEP_SUMMARY

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Lint chart
        run: ct lint --config .github/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: install chart
        run: ct install --config .github/ct.yaml
