---
name: Chart Testing

on:
  pull_request:
    types: 
      - opened
      - synchronize
    paths-ignore:
      - README.md
    
jobs:

  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Lint chart
        run: ct lint  --chart-dirs . --charts .

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          kubectl_version: 'v1.25'

      - name: install chart
        run: ct install --chart-dirs . --charts .