---
name: Chart Testing

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - README.md

env:
  KIND_VERSION: v0.22.0

jobs:

  chart-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        K8S_VERSION:
        - v1.26.14@sha256:5d548739ddef37b9318c70cb977f57bf3e5015e4552be4e27e57280a8cbb8e4f
        - v1.27.10@sha256:e6b2f72f22a4de7b957cd5541e519a8bef3bae7261dd30c6df34cd9bdd3f8476
        - v1.28.7@sha256:9bc6c451a289cf96ad0bbaf33d416901de6fd632415b076ab05f5fa7e4f65c58
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          check-latest: true

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      # docker run -it --rm -v $(pwd):/test --workdir /test quay.io/helmpack/chart-testing ct lint --all --lint-conf ./.github/lintconf.yaml
      - name: Lint chart
        run: ct lint --config .github/ct.yaml --lint-conf .github/lintconf.yaml
        shell: bash

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: kindest/node:${{ matrix.K8S_VERSION }}

      - name: Install charts
        run: ct install --config .github/ct.yaml
        shell: bash