---
name: Chart Testing

on:
  pull_request:
    types: 
      - opened
      - synchronize
    paths-ignore:
      - README.md

env:
  KIND_VERSION: v0.18.0

jobs:

  chart-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        K8S_VERSION:
        - v1.25.8@sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f
        - v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          
      - name: Set up Helm
        uses: azure/setup-helm@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      # docker run -it --rm -v $(pwd):/test --workdir /test quay.io/helmpack/chart-testing ct lint --all --lint-conf ./.github/lintconf.yaml 
      - name: Lint chart
        run: ct lint --config .github/ct.yaml --lint-conf .github/lintconf.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: kindest/node:${{ matrix.K8S_VERSION }}

      - name: Install charts
        run: ct install --config .github/ct.yaml
