---
name: Chart Testing

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - README.md

env:
  KIND_VERSION: v0.20.0

jobs:

  chart-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        K8S_VERSION:
        - v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb
        - v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          check-latest: true

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      # docker run -it --rm -v $(pwd):/test --workdir /test quay.io/helmpack/chart-testing ct lint --all --lint-conf ./.github/lintconf.yaml
      - name: Lint chart
        run: ct lint --config .github/ct.yaml --lint-conf .github/lintconf.yaml
        shell: bash

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: kindest/node:${{ matrix.K8S_VERSION }}

      - name: Install charts
        run: ct install --config .github/ct.yaml
        shell: bash